### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by akrinaldi** [akrinaldi/uiowaj-sjmc-global-media-project#10]
In conversion, some titles and special characters have been altered. If we can find a pattern in these, the process of correcting them can be automated.

**Comment by akrinaldi** [comment]
HispamÃ©rica = Hispamérica

**Comment by akrinaldi** [comment]
PÃ©rsico = Pérsico

PatiÃ±o = Patiño

CondÃ© = Condé

RamÃ­rez = Ramírez

GarcÃ­a = García
GarcÃa = García

RodrÃ­guez = Rodríguez

De los Ãngeles Calvo = De los Ángeles Calvo

MuÃ±oz = Muñoz

MerbilhaÃ¡ = Merbilhaá

TobÃ³n = Tobón

PampÃ­n = Pampín

FernÃ¡ndez = Fernández

PeÃ±a = Peña

HernÃ¡ndez = Hernández

RodÃ³ = Rodó

**Comment by bekdale** [comment]
Fixed the following special characters:

√© -> é
√± -> ñ
√≠ -> í
√Å -> Á
√° -> á
√≥ -> ó
√á -> Ç
√â -> É
√ì -> Ó
√ñ -> Ö
√Ö -> Å
‚Äú -> “
‚Äù -> “
√ò -> Ø
√ú -> Ü
≈† -> Š
≈° -> š
≈Å -> Ł
≈ª -> Ż
≈û -> Ş
√º -> ü
√ß -> ç
ƒü -> ğ
≈Ω -> Ž
≈æ -> ž
≈ü -> ş
√¢ -> â
√∏ -> ø
»ò -> Ș
√§ -> ä
‚Äô -> ’
‚Äò -> ’
√∂ -> ö
√® -> è
√É -> Ã
â‚Ç¨≈ì -> “
‚Äü -> „
‚Ä¶ -> …
‚ãØ -> ⋯
√† -> à
√∫ -> ú
√´ -> ë
√¶ -> æ
√™ -> ê
√£ -> ã
√• -> å
√∞ -> ð
√ü -> ß
√Ä -> À
‚Äì  -> –
√¥ -> ô
√¨-> ì
√Æ -> î
√ª -> û
√≤ -> ò
√Ø -> ï
√µ -> õ
√í -> Ò
√ç -> Í
√ã -> Ë
√π -> ù
√î -> Ô
√Ω -> ý
√à -> È
√ë -> Ñ
√ó -> ×
√õ -> Û
√ô -> Ù
≈Ñ -> ń
≈Ç -> ł
≈´ -> ū
≈£ -> ţ
≈õ -> ś
≈º -> ż
≈ì -> œ
≈ô -> ř
≈± -> ű
≈∫ -> ź
≈ë -> ő
≈© -> ũ
ƒç -> č
ƒΩ -> Ľ 
≈• -> ť
≈â -> ‘
≈è -> ŏ
≈à -> ň
≈≥ -> ų
≈≠ -> ŭ
≈í -> Œ

≈ö -> Ś
≈ê -> ??
ƒå -> Č
≈á -> Ň
≈ï -> ŕ
≈Ø -> ů
≈É -> Ń
ƒá -> ć
ƒó -> ė
ƒ± -> ı
ƒÉ -> ă
»ô -> ș
ƒô -> ę
ƒ∞ -> İ
ƒÖ -> ą
ƒõ -> ě
ƒì -> ē
ƒù‚Ç¨" -> —
ƒ´ -> ī
ƒú‚Ç¨ -> “
ƒê -> Đ
ƒ∫ -> í
ƒë -> đ
ƒâ -> ĉ
ƒù -> ĝ
ƒ©-> ĩ
ƒπ -> Ĺ
