### ISSUE TITLE
Parameters to analyze

### ISSUE THREAD

**Issue by akrinaldi** [akrinaldi/uiowaj-sjmc-global-media-project#2]
So far I am looking for the following parameters:

- Article title
- Author name
- Author affiliation (university, city, country)
- Citations
- Keywords

What other parameters are we interested in?

**Comment by bekdale** [comment]
Based on what we get from the pull, I would add title to the mix. Could be useful to do an analysis based on word frequencies in title and keywords. 

At some point, I want to do manual coding to check to see if volume/issues are guest edited.

May also be fun to check "open access" against country. In many cases, you have to pay $2-3K to make your article open access. I would bet that we'd see more open access articles for resource rich countries.
