### ISSUE TITLE
CSV cleaning

### ISSUE THREAD

**Issue by akrinaldi** [akrinaldi/uiowaj-sjmc-global-media-project#7]
The new CSVs have been uploaded to the GitHub. Half of them are clean. If we could agree upon call terms for each of our columns, that would allow me to create a more uniform master file.

Of the parameters I have so far, I have:
- Issns and eIssns
- title
- author
- uni, city, country affiliations
- vol, issue, pages, date
- url
- open access
- article type

**Comment by bekdale** [comment]
Are "call terms" the same as what I think of as column headers on a spreadsheet? If so, here are few suggestions to shorten/clarify, assuming we will be combining this data with other datasets:

Article_URL
Article_Title
Article_Author
Article_Author_Affiliation
Article_Author_City
Article_Author_University
Article_Volume
Article_Issue
Article_Pages
Article_Date
Article_DOI
Article_CitedBy
Article_Type
Article_OA
Journal_Name
Journal_ISSN 
Journal_eISSN

**Comment by akrinaldi** [comment]
These search parameters look good. I will swap Article_Author_Affiliation for Article_Author_Country to account for all columns.

**Comment by akrinaldi** [comment]
Added the following:

Article_Pub_Year
Article_OAb (binary)
Article_OAtf (T/F)
Aggregation_Type
