### ISSUE TITLE
Data Missing

### ISSUE THREAD

**Issue by bekdale** [akrinaldi/uiowaj-sjmc-global-media-project#8]
After combining the individual CSV files, it looks like we're missing data. Need to resolve and repull or pull missing data only.

**Comment by bekdale** [comment]
1) The issn_loop.ipynb file has the ISSN list from the 2018 data and needs to be updated to include the 2019 data (~400 journals). 

2) Per John's email, we need to add a sleep at the end of our loop to space our our requests. 

Add to loop: import time

To your imports, and add: time.sleep(0.12)

**Comment by akrinaldi** [comment]
We can run back through it all, but after this last pull, I think that's all.
