### ISSUE TITLE
Floating university affiliations

### ISSUE THREAD

**Issue by akrinaldi** [akrinaldi/uiowaj-sjmc-global-media-project#9]
Some university affiliations are blank, while some are floating to the right of the main data with seemingly no match.

**Comment by bekdale** [comment]
These entries are for authors with multiple affiliations. Keeping the dataset for now in case we want to divide up someone's affiliation when counting. If we want to stay with first affiliation only, we can also do a check to see if analysis would change if if we included additional affiliations.
